-- MySQL Script generated by MySQL Workbench
-- Thu Jan 25 12:24:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kukkakauppa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kukkakauppa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kukkakauppa` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `kukkakauppa` ;

-- -----------------------------------------------------
-- Table `kukkakauppa`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukkakauppa`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(64) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `type` INT NOT NULL DEFAULT 0,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `kukkakauppa`.`products_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukkakauppa`.`products_meta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meta_type` INT NULL,
  `meta_value` TINYTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `kukkakauppa`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kukkakauppa`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meta_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `info` VARCHAR(255) NOT NULL,
  `price` DECIMAL(13,2) NOT NULL,
  `vat` INT NOT NULL,
  `creator` INT NOT NULL,
  `published_status` INT NOT NULL DEFAULT 0,
  `published_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_products_meta_idx` (`meta_id` ASC),
  CONSTRAINT `fk_products_products_meta`
    FOREIGN KEY (`meta_id`)
    REFERENCES `kukkakauppa`.`products_meta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
